apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
- https://raw.githubusercontent.com/longhorn/longhorn/v1.9.1/deploy/longhorn.yaml
- route.yaml

configMapGenerator:
  - name: longhorn-storageclass
    namespace: longhorn-system
    files:
      - storageclass.yaml
    behavior: merge
    options:
      disableNameSuffixHash: true
  - name: longhorn-envs
    literals:
      - CSI_ATTACHER_REPLICA_COUNT=1
      - CSI_PROVISIONER_REPLICA_COUNT=1
      - CSI_RESIZER_REPLICA_COUNT=1
      - CSI_SNAPSHOTTER_REPLICA_COUNT=1
  
patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/rgocd.argoproj.io~1sync-options
      value: "ServerSideApply=true"
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: longhorn-manager
  patch: |-
    - op: replace #action 
      path: /spec/template/spec/volumes/4/hostPath/path
      value: /data/longhorn
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
        - configMapRef:
            name: longhorn-envs
- target:
    group: apps
    version: v1
    kind: Deployment
    name: longhorn-ui
  patch: |-
    - op: replace #action 
      path: /spec/replicas
      value: 1