apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/envoyproxy/gateway/releases/download/v1.5.0/install.yaml

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/rgocd.argoproj.io~1sync-options
      value: "ServerSideApply=true"