apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
  - repoURL: https://charts.longhorn.io
    targetRevision: 1.9.1
    chart: longhorn
    helm:
      parameters:
        - name: persistence.defaultClassReplicaCount
          value: "1"
        - name: longhornUI.replicas
          value: "1"
        - name: csi.attacherReplicaCount
          value: "1"
        - name: csi.provisionerReplicaCount
          value: "1"
        - name: csi.resizerReplicaCount
          value: "1"
        - name: csi.snapshotterReplicaCount
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  # add ignoreDifferences to prevent preserveUnknownFields field from make causing the application to be out of sync
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers: ["/spec/preserveUnknownFields"]