apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cluster
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: Gateway
      name: envoy-proxy
      namespace: envoy-gateway-system
  hostnames:
    - "kubernetes.jynolen.fr"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: kubernetes
          port: 443
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: cluster-tls
  namespace: default
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: kubernetes
    sectionName: https
  validation:
    caCertificateRefs:
    - name: kube-root-ca.crt
      group: ''
      kind: ConfigMap
    hostname: kubernetes