apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"

resources:
- namespace.yaml
- server.yaml
- routes.yaml
- policy.yaml
- roles.yaml