---
apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicyBinding
metadata:
  name: admin-role
spec:
  vaultRoleName: admin
  vaultRef:
    name: vault
  policies:
  - ref: admin
  subjectRef:
    oidc:
      boundAudiences: 
      - vault
      userClaim: email
      groupClaim: roles
      tokenMaxTTL: 3600
      verboseOidcLogging: true
      allowedRedirectUris:
      - https://vault.jynolen.fr/ui/vault/auth/oidc/oidc/callback
      - https://vault.jynolen.fr/v1/auth/oidc/oidc/callback