apiVersion: kubevault.com/v1alpha2
kind: VaultServer
metadata:
  name: vault
spec:
  replicas: 1
  version: 1.18.4
  backend:
    inmem: {}
  unsealer:
    secretShares: 4
    secretThreshold: 2
    mode:
      kubernetesSecret:
        secretName: vault-keys
  authMethods:
    - type: oidc
      path: oidc
      oidcConfig:
        oidcDiscoveryURL: https://keycloak.jynolen.fr/realms/kubernetes
        oidcClientID: vault
        credentialSecretRef:
          name: vault-oidc-secret
        defaultRole: admin
    - path: kubernetes	
      type: kubernetes