apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: postgresql-system/cluster
  # extensions:
  # - name: bloom
  #   ensure: present
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: generator
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: "0"
  target:
    name: keycloak
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: generator