apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: postgresql-system/cluster
  # extensions:
  # - name: bloom
  #   ensure: present
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: "0"
  target:
    name: keycloak
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: external-secrets/generator