apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: cluster-rw.postgresql-system.svc.cluster.local
    database: keycloak-db
    usernameSecret:
      name: keycloak-db-user
      key: username
    passwordSecret:
      name: keycloak-db-user
      key: password
  ingress:
    enabled: false
  http:
    httpEnabled: true
  hostname:
    hostname: keycloak.jynolen.fr
    strict: false
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  features:
    enabled: []