---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: generator
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: "0"
  target:
    name: keycloak-db-user
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: "postgresql-system"
      data:
        username: keycloak
        password: "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: generator