apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd.git//manifests/cluster-install?ref=v3.1.1

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
    options:
      disableNameSuffixHash: true
