apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd.git//manifests/cluster-install?ref=v3.1.1

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
    options:
      disableNameSuffixHash: true
  - name: argocd-cm
    behavior: merge
    literals:
      - url=https://argocd.jynolen.fr
    files:
      - oidc.config
    options:
      disableNameSuffixHash: true
  - name: argocd-rbac-cm
    behavior: merge
    literals:
      - scopes="[groups, roles:argocd]"
    files:
      - policy.csv
    options:
      disableNameSuffixHash: true

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/rgocd.argoproj.io~1sync-options
      value: "ServerSideApply=true"