apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jynolen/peros-cluster
    path: echoserver
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
