apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://helm.mittwald.de
    targetRevision: v2.12.0
    chart: kubernetes-replicator
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-replicator 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true