apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-wave: '-1'

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/rgocd.argoproj.io~1sync-options
      value: "ServerSideApply=true"

resources:
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/refs/tags/26.3.3/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/refs/tags/26.3.3/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/refs/tags/26.3.3/kubernetes/kubernetes.yml