apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cluster-bundle
  namespace: cert-manager
spec:
  sources:
  - useDefaultCAs: true
  - configMap:
      name: "kube-root-ca.crt"
      key: "ca.crt"
  target:
    configMap:
      key: "ca.crt"